feat: Expose metadata to plugins as object
Netflix/metaflow-ui pull request #51
Opened 2022-01-12 10:26 UTC by rsanteri

### Requirements for a pull request

- [x] Unit tests related to the change have been updated 
- [x] Documentation related to the change has been updated 

### Description of the Change

Update data type of metadata exposed to plugins. Before data type was raw metadata array, Metadata[]. Now we expose single object with field_name: value pairs.

2022-01-20 21:10 UTC, obgibson approved these changes

2022-01-21 18:43 UTC, obgibson requested changes
Where can I get `ts_epoch` from now?

2022-01-22 01:33 UTC, skirdey approved these changes

2022-01-24 10:18 UTC, rsanteri commented
> Where can I get `ts_epoch` from now?

With this change it is not available. Which ts_epoch would you need here? Run, Task, Metadata?

2022-01-24 16:22 UTC, merged